from . import tab1_prompt
from . import tab2_prompt
from . import tab3_prompt
from . import tab4_prompt
from . import tab5_prompt
from . import tab6_prompt
from . import tab7_prompt
from . import tab8_prompt
from . import tab9_prompt
